### ISSUE TITLE
Sortabular doesn't work with integer values resolved with resolve.byFunction

### ISSUE THREAD

**Issue by daniula** [reactabular/sortabular#1]
I have defined columns:
```
[
  { property: 'date', header: { label: 'Date', formatters: [sortableHeader] } },
  { property: 'columnA', header: { label: 'Column A', formatters: [sortableHeader] } },
  { property: 'columnB', header: { label: 'Column B', formatters: [sortableHeader] } },
  { property: 'total', header: { label: 'Total', formatters: [sortableHeader] }, cell: {
    resolve: (x, { rowData }) => _.sum(_.values(_.omit(rowData, 'date')))
  } }
]
```
and I'm trying to add sortabular for all those columns. All works fine except total because of those lines: https://github.com/reactabular/sortabular/blob/master/src/sorter.js#L32-L40

In this case `row.total` is always returned with value `undefined`.

Why `resolvedValue` does have to have `toLowerCase` to be returned?

**Comment by bebraw** [comment]
Hi,

It has been developed strings in mind. That said, I wouldn't mind a PR that extends it to work with other types. If you PR, remember to write good tests for the new functionality.
