### ISSUE TITLE
`classnames` package should be in project dependencies

### ISSUE THREAD

**Issue by tomiberes** [reactabular/sortabular#10]
Since npm, doesn't install `peerDependencies` of dependent packages while installing top level project dependencies anymore since npm@3, `classnames` should be listed in `dependencies` of this project explicitly.
See [src/sort.js#L1](https://github.com/reactabular/sortabular/blob/master/src/sort.js#L1)

**Comment by bebraw** [comment]
It's this way by design as I expect the user to control the version of `classnames`, `lodash`, etc.

**Comment by tomiberes** [comment]
In my current case the project isn't using `classnames`, and the only place where it's required is the mentioned module from this package.
Wouldn't it make more sense to include it as a direct dependency? Since it won't work without it.

**Comment by bebraw** [comment]
You'll have to install `classnames` explicitly to the project in that case, yup.
