### ISSUE TITLE
predicate is not a function

### ISSUE THREAD

**Issue by szare** [reactabular/sortabular#6]
when I'm using the Example, I receive the following error:
`resolve.nested - Failed to find "name.last" property from Object {id: 101, name: Object, age: 43}
`
```
bundle.js:35685 Uncaught TypeError: predicate is not a function
    at baseFindIndex (http://127.0.0.1:3333/js/bundle.js:35685:10)
    at findIndex (http://127.0.0.1:3333/js/bundle.js:37302:11)
    at http://127.0.0.1:3333/js/bundle.js:36468:18
    at Object.getColumn (http://127.0.0.1:3333/js/bundle.js:28627:32)
    at http://127.0.0.1:3333/js/bundle.js:41445:34
    at Array.forEach (native)
    at http://127.0.0.1:3333/js/bundle.js:41444:34
    at http://127.0.0.1:3333/js/vendor.js:21084:15
    at Array.reduceRight (native)
    at http://127.0.0.1:3333/js/vendor.js:21083:18 
```

**Comment by bebraw** [comment]
The example expects the name to be an object that contains first and last fields. Maybe you want to drop `resolve.nested`.

The error should be made clearer.

**Comment by szare** [comment]
It was my `lodash` problem, after installing the `lodash` for second time, the problem solved.

**Comment by bebraw** [comment]
Ok, cool to hear. 👍 

I think I'll bump the peer dependency to lodash 4 to avoid this in the future.

**Comment by szare** [comment]
I'm using    ` "lodash": "^4.17.4",` at the moment.

**Comment by bebraw** [comment]
Yeah, that's enough. I bumped the peer dep.
